### GENERAL SETTINGS ###

# Site settings
title: Pewee
description: ""
baseurl: ""
url: "http://peweestore.github.io/"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "orange"
  primary_rgb: "black" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "black"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  home_feature: "black"
  home_color: "orange"
